Controllers/UserAccessController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using SMSApp.Models;
using SMSApp.Models.SC;
using System.Diagnostics;
using System.Security.Claims;
using WebTemplate.Models.BLL;
using System.Data;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace SMSApp.Controllers
{
    [Authorize]
    public class UserAccessController : Controller
    {
        private readonly ILogger<UserAccessController> _logger;
        private IConfiguration Configuration;

        public UserAccessController(ILogger<UserAccessController> logger, IConfiguration _configuration)
        {
            _logger = logger;
            Configuration = _configuration;
        }

        public IActionResult Privacy()
        {
            return View();
        }

        // All User Access List
        [HttpGet]
        public ActionResult Index()
        {
            return View("UserAccessList");
        }

        // Redirect to new User Access Page
        [HttpGet]
        public ActionResult New()
        {
            this.FillUsersList();

            UserAccessSC mUserAccessSC = new UserAccessSC();
            mUserAccessSC.IsActive = "1";

            return View("UserAccessForm", mUserAccessSC);
        }

        // GEt All Users List
        public void FillUsersList()
        {
            SelectList mSelectList = null;
            Select2DropDown mSelect2DropDown = null;
            IList<Select2DropDown> mSelect2DropDownLst = null;

            mSelect2DropDownLst = new List<Select2DropDown>();
            mSelect2DropDown = new Select2DropDown();

            mSelectList = new SelectList(mSelect2DropDownLst.ToArray(), "Value", "Text");

            ViewData["UsersList"] = mSelectList;
        }

        // Save User Access 
        [HttpPost]
        public IActionResult SaveUserAccess(UserAccessSC vUserAccessSC)
        {
            if (vUserAccessSC.FloorId == null)
            {
                return Json(new
                {
                    IsSuccess = "N",
                    ErrorMessage = "The 'フロア' Field is required"
                });
            }

            UserAccessBLL mUserAccessBLL = null;

            mUserAccessBLL = new UserAccessBLL();

            vUserAccessSC.IsEdit = vUserAccessSC.UserAccessId == null ? "N" : "Y";
            vUserAccessSC.CurrUserId = User.GetUserId();

            mUserAccessBLL.SaveUserAccess(vUserAccessSC, Configuration);

            return Json(new
            {
                IsSuccess = "Y"
            });
        }

        // View User Access List
        [HttpPost]
        public IActionResult ViewUserAccessList()
        {
            UserAccessBLL mUserAccessBLL = null;
            DataSet mDset = null;

            mUserAccessBLL = new UserAccessBLL();

            mDset = mUserAccessBLL.ViewUserAccessList(User.GetUserId().ToString(), Configuration);

            return Json(JsonConvert.SerializeObject(mDset));
        }

        // Edit User Access List
        [HttpGet]
        public ActionResult Edit(String id)
        {
            UserAccessBLL mUserAccessBLL = null;
            UserAccessSC mUserAccessSC = null;
            string mUserId = string.Empty;
            string mIsSuccess = string.Empty;

            mUserAccessBLL = new UserAccessBLL();
            mUserAccessSC = new UserAccessSC();

            mUserId = User.GetUserId();

            // Controller Validation
            mIsSuccess = mUserAccessBLL.UserAccessGetByIdValidate(id, mUserId, Configuration);

            if (mIsSuccess == "0")
            {
                return RedirectToAction("Index", "UnAuthorize");
            }

            mUserAccessSC = mUserAccessBLL.UserAccessGetById(id, Configuration);

            return View("UserAccessForm", mUserAccessSC);
        }

        // Get All User List on page
        [HttpPost]
        public IActionResult GetAllUsersList()
        {
            UserAccessBLL mUserAccessBLL = null;
            DataSet mDset = null;

            mUserAccessBLL = new UserAccessBLL();

            mDset = mUserAccessBLL.GetAllUsersList(Configuration);

            return Json(JsonConvert.SerializeObject(mDset));
        }

        // Get ALl Floor List on page
        [HttpPost]
        public IActionResult GetAllFloorList(string vType)
        {
            UserAccessBLL mUserAccessBLL = null;
            DataSet mDset = null;
            string mUserId = string.Empty;

            mUserAccessBLL = new UserAccessBLL();

            mUserId = User.GetUserId();

            mDset = mUserAccessBLL.GetAllFloorList(mUserId, vType, Configuration);

            return Json(JsonConvert.SerializeObject(mDset));
        }

        // Get All Floor
        [HttpPost]
        public IActionResult GetAllFloor()
        {
            FloorBLL mFloorBLL = null;
            DataSet mDset = null;
            string vCurrUsrId = string.Empty;

            mFloorBLL = new FloorBLL();
            vCurrUsrId = User.GetUserId();

            mDset = mFloorBLL.GetAllFloor(Configuration);

            return Json(JsonConvert.SerializeObject(mDset));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

Views/UserAccess/UserAccessForm.cshtml
@model SMSApp.Models.SC.UserAccessSC

@{
    ViewBag.Title = "UserRole";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/js/Appjs/UserAccess/UserAccessForm.js"></script>

<script type="text/javascript">

    function OnUserAccessSuccess(data) {

        if (data.isSuccess == "N") {
            $("#dvErrors").html(data.errorMessage);
        }
        else {
            swal({
                title: "SUCCESS!",
                text: "正常に完了しました。",
                type: "success",
                confirmButtonText: "OK"
            },
                function (isConfirm) {
                    window.location.href = '@Url.Action("Index","UserAccess")';
                });
        }
    }

    function RedirectBack() {

        window.location.href = '@Url.Action("Index","UserAccess")';

        return false;
    }

</script>

<div ng-controller="UserAccessFormCtrl">
    <form action="/UserAccess/SaveUserAccess" data-ajax="true" data-ajax-failure="OnFailure"
          data-ajax-method="POST" data-ajax-success="OnUserAccessSuccess" id="form0" method="post" enctype="multipart/form-data">

        <div class="col-12 PageMargin">
            <section class="box">
                <header class="panel_header">
                    @if (Model != null && Model.UserAccessId != null)
                    {
                        <h2 class="title float-left">権限管理</h2>
                    }
                    else
                    {
                        <h2 class="title float-left">権限管理</h2>
                    }
                </header>
                <div class="content-body">
                    <div class="row">
                        <div class="col-6 col-md-6 col-lg-6">
                            <div class="form-group">
                                <label class="form-label title">
                                    フロア
                                    <span class="text text-danger">*</span>
                                </label>
                                <div class="controls">
                                    @if (Model != null && Model.FloorId != null)
                                    {
                                        @Html.DisplayFor(model => model.FloorName,new { @id = "txtFloor"})
                                        @Html.HiddenFor(model => model.FloorId,new { @id = "hiddFloor"})
                                    }
                                    else
                                    {
                                        <div class="input-group sm-3">
                                            <select id="ddlFloor" class="form-control ddlSelect2Single" ng-model="FloorId" on-Finish-Render>
                                                <option ng-value="'0'">--Select--</option>
                                                <option ng-selected="FloorId == item.FloorId" ng-repeat="item in FloorList" ng-value="item.FloorId">
                                                    {{item.FloorName}}
                                                </option>
                                            </select>
                                            <div id="dvErrors" class="text-danger">
                                            </div>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                        <div class="col-6 col-md-6 col-lg-6">
                            <div class="form-group">
                                <label class="form-label">
                                    権限管理メモ
                                </label>
                                <div class="controls">
                                    @Html.TextBoxFor(model => model.FloorDesc, new { @class = "form-control", @placeholder = "権限管理メモ", @autocomplete = "off" })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6 col-md-6 col-lg-6">
                            <div class="form-group">
                                <label class="form-label">
                                    ユーザの選択
                                    <span class="text text-danger">*</span>
                                </label>
                                <div class="controls">
                                    <div class="input-group sm-3">
                                        <select id="ddlUser" class="form-control ddlSelect2Single" ng-model="UserId" on-Finish-Render>
                                            <option ng-value="'0'">--Select--</option>
                                            <option ng-repeat="item in UserAccessList" ng-value="item.UserId">
                                                {{item.Name}}
                                            </option>
                                        </select>
                                    </div>
                                    <button type="button" ng-click="AddUsersList()">
                                        <span class="fa fa-plus"></span>
                                        追加
                                    </button>
                                </div>
                            </div>
                        </div>
                        <div class="col-6 col-md-6 col-lg-6">
                            <div class="form-group">
                                <label class="form-label">
                                    ステータス
                                    <span class="text text-danger">*</span>
                                </label>
                                <div class="controls">
                                    @Html.RadioButtonFor(model => model.IsActive, "1", new { @id = "rdoStatusActive", @checked = "checked" })
                                    <label class="form-label" for="rdoStatusActive">有効</label>
                                    @Html.RadioButtonFor(model => model.IsActive, "0", new { @id = "rdoStatusInActive" })
                                    <label class="form-label" for="rdoStatusInActive">無効</label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 col-md-12 col-lg-12">
                            <table id="example-11" class="display table-sm table-sm table-bordered" cellspacing="0" width="100%">
                                <colgroup>
                                    <col wdith="3%" />
                                    <col wdith="55%" />
                                    <col wdith="35%" />
                                    <col wdith="*" />
                                </colgroup>
                                <thead>
                                    <tr>
                                        <th width="10%">Sr No</th>
                                        <th width="45%">ユーザ名</th>
                                        <th width="35%">権限種別</th>
                                        <th width="10%">ユーザ削除</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr ng-repeat="item in AllMapUsers|filter: { IsType : '!D' }" ng-if="AllMapUsers.length > 0">
                                        <td ng-bind="item.RowId"></td>
                                        <td ng-bind="item.UserName"></td>
                                        <td>
                                            <label for="lblView{{item.RowId}}">
                                                <input id="lblView{{item.RowId}}" ng-model="item.Select" value="Vw" type="radio" name="search-type{{item.RowId}}">
                                                参照
                                            </label>
                                            <label for="UseANDView{{item.RowId}}">
                                                <input id="UseANDView{{item.RowId}}" ng-model="item.Select" value="UVw" type="radio" name="search-type{{item.RowId}}">
                                                利用者
                                            </label>
                                        </td>
                                        <td>
                                            <button class="btn btn-sm" type="button" ng-click="RemoveUser(item.RowId);">
                                                <span class="fa fa-remove"></span>
                                            </button>
                                        </td>
                                    </tr>
                                    <tr ng-if="AllMapUsers.length == 0">
                                        <td colspan="4">
                                            <span class="text text-danger">該当する情報はありません</span>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <br />
                    <div class="row">
                        <div class="col-12 col-md-9 col-lg-8 padding-bottom-30">
                            <div class="text-left">
                                <button type="submit" class="btn btn-primary" onclick="return SaveUserAccess();">
                                    <span class="fa fa-save"></span>
                                    保存
                                </button>
                                <button type="button" class="btn" onclick="return RedirectBack();">
                                    <span class="fa fa-undo"></span>
                                    戻る
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
        <div>
            @Html.HiddenFor(model => model.UserAccessId, new { @id = "txtUserAccessId"})
            @Html.HiddenFor(model => model.FloorId, new { @id = "txtFloorId"})
            @Html.HiddenFor(model => model.UserJSON, new { @id = "txtUserJSON"})
        </div>
    </form>
</div>

Views/UserAccess/UserAccessList.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/js/Appjs/UserAccess/UserAccessView.js"></script>

<script type="text/javascript">

    function AddUserAccess() {

        window.location.href = '@Url.Action("New","UserAccess")';
        return false;

    }

</script>

<div ng-controller="UserAccessViewCtrl">
    <div class="col-xl-12 PageMargin">
        <section class="box ">
            <header class="panel_header">
                <h2 class="title float-left" style="width:100% !important">
                    <span>利用管理</span>
                    <button type="button" class="btn btn-xs btn-primary float-right" onclick="AddUserAccess();" style="margin-right:2%">
                        <span class="fa fa-plus">
                            新規
                        </span>
                    </button>
                </h2>
            </header>
            <div class="content-body">
                <div class="row">
                    <div class="col-12">
                    </div>
                    <div class="col-12">
                        <table id="example-11" class="display table table-hover table-condensed" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th style="5%"></th>
                                    <th style="5%">Sr No</th>
                                    <th style="25%">フロア</th>
                                    <th style="25%">権限管理メモ</th>
                                    <th style="10%">ステータス</th>
                                    <th style="5%">バージョン</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr dir-paginate="item in UserAccessList | orderBy: 'RowId' | itemsPerPage: pageSize | record:'currentPage':this">
                                    <td>
                                        <span style="cursor:pointer" ng-click="RedirectUserAccessToEdit(item.UserAccessId);">
                                            <i class="fa fa-edit"></i>
                                        </span>
                                    </td>
                                    <td ng-bind="item.RowId"></td>
                                    <td ng-bind="item.FloorName"></td>
                                    <td ng-bind="item.FloorDesc"></td>
                                    <td>
                                        <span class="badge badge-primary" ng-bind="item.IsActive" ng-show="item.IsActive == 'Active'"></span>
                                        <span class="badge badge-defaut" ng-bind="item.IsActive" ng-show="item.IsActive == 'InActive'"></span>
                                    </td>
                                    <td ng-bind="item.CreatedOn"></td>
                                </tr>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="6">
                                        <div class="text-center pull-right">
                                            <dir-pagination-controls boundary-links="true" on-page-change="pageChangeHandler(newPageNumber)"
                                                                     template-url="@Url.Content("~/dirpagination.tpl.html")">
                                            </dir-pagination-controls>
                                        </div>
                                    </td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>