Controllers/FloorController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using SMSApp.Models;
using SMSApp.Models.SC;
using System.Diagnostics;
using System.Security.Claims;
using WebTemplate.Models.BLL;
using System.Data;
using Newtonsoft.Json;
using SMSApp.Models.DAL;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Formatters;

namespace SMSApp.Controllers
{
    [Authorize]
    public class FloorController : Controller
    {
        private readonly ILogger<FloorController> _logger;
        private IConfiguration Configuration;

        private readonly IWebHostEnvironment _webHostEnvironment;

        public FloorController(ILogger<FloorController> logger, IConfiguration _configuration, IWebHostEnvironment? webHostEnvironment)
        {
            _logger = logger;
            Configuration = _configuration;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View("FloorList");
        }

        // New Floor Addition
        [HttpGet]
        public ActionResult New()
        {
            FloorSC mFloorSC = new FloorSC();
            mFloorSC.UsernameFontsize = "11";
            mFloorSC.Status = "1";

            return View("FloorForm", mFloorSC);
        }

        // Save Floor
        [HttpPost]
        public IActionResult SaveFloorData(FloorSC vFloorSC, string btnSave)
        {
            string mFileName = string.Empty;
            string IsFile = "N";

            try
            {
                FloorBLL mFloorBLL = null;
                ImageSC mImageSC = null;
                ImageDAL mImageDAL = null;

                string mFilePath = string.Empty;
                string mOrgPath = string.Empty;

                mFloorBLL = new FloorBLL();
                mImageSC = new ImageSC();

                mImageDAL = new ImageDAL(Configuration);

                if (btnSave == "Save")
                {
                    if (vFloorSC.FloorId == null && vFloorSC.FloorImage == null)
                    {
                        return Json(new
                        {
                            IsSuccess = "N",
                            ErrorMessage = "The '詳細' Field is required"
                        });
                    }

                    if (vFloorSC.FloorName == null)
                    {
                        return Json(new
                        {
                            IsSuccess = "N",
                            ErrorMessage = "The 'フロア名' Field is required"
                        });
                    }

                    if (vFloorSC.FloorId == null)
                        vFloorSC.IsEdit = "N";
                    else if (vFloorSC.FloorImage != null)
                        vFloorSC.IsEdit = "N";
                    else if (vFloorSC.FloorId != null)
                        vFloorSC.IsEdit = "Y";

                    vFloorSC.ControllerId = !string.IsNullOrEmpty(vFloorSC.ControllerId) ? vFloorSC.ControllerId : "0";
                    vFloorSC.CurrUserId = User.GetUserId();

                    if (vFloorSC.FloorImage != null)
                    {
                        mImageSC.IsEdit = vFloorSC.IsEdit;
                        mImageSC.ImageName = Path.GetFileName(vFloorSC.FloorImage.FileName);
                        mImageSC.CurrUserId = User.GetUserId();
                        mImageSC.OrgImagepath = Path.Combine(_webHostEnvironment.WebRootPath, "Uploads", "FloorImage");
                        mImageSC.TestPath = _webHostEnvironment.WebRootPath;
                    }

                    mFloorBLL.SaveFloor(mImageSC, vFloorSC, Configuration);

                }
                else
                {
                    vFloorSC.CurrUserId = User.GetUserId();

                    if (vFloorSC.FloorImage != null)
                    {
                        mImageSC.ImageName = Path.GetFileName(vFloorSC.FloorImage.FileName);
                        mImageSC.OrgImagepath = Path.Combine(_webHostEnvironment.WebRootPath, "Uploads", "FloorTempImage", vFloorSC.CurrUserId.ToString());

                        if (!Directory.Exists(mImageSC.OrgImagepath))
                        {
                            Directory.CreateDirectory(mImageSC.OrgImagepath);
                        }

                        string[] mFile = Directory.GetFiles(mImageSC.OrgImagepath);

                        if (mFile != null && mFile.Length > 0)
                        {
                            foreach (string f in mFile)
                            {
                                System.IO.File.Delete(f);
                            }
                        }


                        mFileName = vFloorSC.FloorImage.FileName;

                        mFilePath = mImageSC.OrgImagepath + "\\" + mFileName;

                        using (var stream = System.IO.File.Create(mFilePath))
                        {
                            vFloorSC.FloorImage.CopyTo(stream);
                        }

                        IsFile = "Y";
                    }
                }
            }
            catch (Exception ex)
            {
                System.IO.File.AppendAllText(_webHostEnvironment.WebRootPath + "\\ErrorLog.txt", ex.Message.ToString());
                System.IO.File.AppendAllText(_webHostEnvironment.WebRootPath + "\\ErrorLog.txt", Environment.NewLine);
                System.IO.File.AppendAllText(_webHostEnvironment.WebRootPath + "\\ErrorLog.txt", ex.StackTrace.ToString());
            }

            return Json(new
            {
                IsSuccess = "Y",
                IsFile = IsFile,
                FileName = mFileName
            });
        }

        //Save Floor Mapping
        [HttpPost]
        public IActionResult SaveMapFloor(FloorMapSC vFloorMapSC)
        {
            FloorBLL mFloorBLL = null;

            mFloorBLL = new FloorBLL();

            vFloorMapSC.IsEdit = vFloorMapSC.Id == null ? "N" : "Y";
            vFloorMapSC.CurrUserId = User.GetUserId();

            vFloorMapSC.SeatDetails = !string.IsNullOrEmpty(vFloorMapSC.SeatDetails) ? vFloorMapSC.SeatDetails : "";

            mFloorBLL.SaveFloorMap(vFloorMapSC, Configuration);

            return Json(new
            {
                IsSuccess = "Y"
            });
        }

        //View Floor List
        [HttpPost]
        public IActionResult ViewFloorList(string vIsActive)
        {
            FloorBLL mFloorBLL = null;
            DataSet mDset = null;

            mFloorBLL = new FloorBLL();

            mDset = mFloorBLL.ViewFloorList(User.GetUserId().ToString(), vIsActive, Configuration);

            return Json(JsonConvert.SerializeObject(mDset));
        }

        //Get User By Id
        [HttpGet]
        public ActionResult Edit(String id)
        {
            UserBLL mUserBLL = null;
            UserSC mUserSC = null;

            mUserBLL = new UserBLL();
            mUserSC = new UserSC();

            mUserSC = mUserBLL.UserGetById(id, Configuration);

            return View("AddUser", mUserSC);
        }

        //Update Floor List
        [HttpGet]
        public ActionResult EditFloor(String id)
        {
            FloorBLL mFloorBLL = null;
            FloorSC mFloorSC = null;
            string mUserId = string.Empty;
            string mIsSuccess = string.Empty;

            mFloorBLL = new FloorBLL();
            mFloorSC = new FloorSC();

            mUserId = User.GetUserId();

            // Floor Validation
            mIsSuccess = mFloorBLL.FloorGetByIdValidate(id, mUserId, Configuration);

            if (mIsSuccess == "0")
            {
                return RedirectToAction("Index", "UnAuthorize");
            }

            mFloorSC = mFloorBLL.FloorGetById(id, mUserId, Configuration);

            return View("FloorForm", mFloorSC);
        }

        //Edit Floor Map List
        [HttpGet]
        public ActionResult EditMapFloor(String id, string FloorMapId, string vType)
        {
            FloorBLL mFloorBLL = null;
            FloorMapSC mFloorMapSC = null;
            FloorSC mFloorSC = null;
            string mUserId = string.Empty;

            mFloorBLL = new FloorBLL();
            mFloorMapSC = new FloorMapSC();
            mFloorSC = new FloorSC();

            mUserId = User.GetUserId();

            mFloorSC = mFloorBLL.FloorGetById(id, mUserId, Configuration);

            mFloorMapSC.FloorId = Convert.ToInt32(id);
            mFloorMapSC.ImagePath = mFloorSC.ImagePath;

            // Get Floor Details
            mFloorMapSC.FloorMapLst = mFloorBLL.FloorMapGetById(mFloorMapSC.FloorId.ToString(), FloorMapId, vType, Configuration);
            mFloorMapSC.IsActive = "1";
            mFloorMapSC.FloorName = mFloorSC.FloorName;

            mFloorMapSC.width = mFloorSC.Width;
            mFloorMapSC.height = mFloorSC.Height;

            if (mFloorMapSC.FloorMapLst != null && mFloorMapSC.FloorMapLst.Count > 0)
                mFloorMapSC.FloorMapJSON = JsonConvert.SerializeObject(mFloorMapSC.FloorMapLst);

            ViewBag.UserId = User.GetUserId();
            ViewBag.Width = mFloorSC.Width;
            ViewBag.Height = mFloorSC.Height;

            return View("FloorMap", mFloorMapSC);
        }


        [HttpGet]
        public PartialViewResult OpenSeatSearch(String id, string FloorMapId, string vType)
        {
            FloorBLL mFloorBLL = null;
            FloorMapSC mFloorMapSC = null;
            FloorSC mFloorSC = null;
            string mUserId = string.Empty;

            mFloorBLL = new FloorBLL();
            mFloorMapSC = new FloorMapSC();
            mFloorSC = new FloorSC();

            mUserId = User.GetUserId();

            mFloorSC = mFloorBLL.FloorGetById(id, mUserId, Configuration);

Controllers/SeatBookController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SMSApp.Models;
using SMSApp.Models.SC;
using System.Data;
using System.Diagnostics;
using WebTemplate.Models.BLL;

namespace SMSApp.Controllers
{
    [Authorize]
    public class SeatBookController : Controller
    {
        private readonly ILogger<SeatBookController> _logger;
        private IConfiguration Configuration;

        public SeatBookController(ILogger<SeatBookController> logger, IConfiguration _configuration)
        {
            _logger = logger;
            Configuration = _configuration;
        }

        public IActionResult Privacy()
        {
            return View();
        }

        // Get All Seat List
        [HttpGet]
        public ActionResult Index()
        {
            SeatBookSC mSeatBookSC = new SeatBookSC();
            DataSet mDset = new DataSet();
            FloorBLL mFloorBLL = new FloorBLL();

            mSeatBookSC.IsWFH = "0";

            mDset = mFloorBLL.IsUserWFH(User.GetUserId().ToString(), Configuration);

            if (mDset != null && mDset.Tables.Count > 0 && mDset.Tables[0].Rows.Count > 0)
            {
                mSeatBookSC.IsWFH = mDset.Tables[0].Rows[0]["IsWFH"].ToString();
            }

            return View("SeatBookList", mSeatBookSC);
        }

        // Open Seat Search Page
        [HttpGet]
        public ActionResult Search()
        {
            return View("SeatBookSearch");
        }

        // Save WFH Users
        [HttpPost]
        public IActionResult SaveWFH(string IsWFH)
        {
            FloorBLL mFloorBLL = null;
            FloorMapSC mFloorMapSC = null;

            mFloorBLL = new FloorBLL();
            mFloorMapSC = new FloorMapSC();

            mFloorMapSC.IsEdit = mFloorMapSC.Id == null ? "N" : "Y";

            mFloorMapSC.FloorId = null;
            mFloorMapSC.UserId = Convert.ToInt32(User.GetUserId());
            mFloorMapSC.FloorMapId = null;
            mFloorMapSC.CurrUserId = User.GetUserId();
            mFloorMapSC.IsWFH = IsWFH;

            mFloorBLL.BookSeat(mFloorMapSC, Configuration);

            return Json(new
            {
                IsSuccess = "Y"
            });
        }

        // Checkout functionality
        [HttpPost]
        public IActionResult CheckOut()
        {
            FloorBLL mFloorBLL = null;
            string mCurrUsrId = string.Empty;

            mFloorBLL = new FloorBLL();
            mCurrUsrId = User.GetUserId();

            mFloorBLL.CheckOut(mCurrUsrId, Configuration);

            return Json(new
            {
                IsSuccess = "Y"
            });
        }

        // Seat Book Checkright for IsWFH or not
        [HttpPost]
        public IActionResult SeatBookCheckRights()
        {
            FloorBLL mFloorBLL = null;
            string mCurrUsrId = string.Empty;
            DataSet mDset = new DataSet();

            mFloorBLL = new FloorBLL();
            mCurrUsrId = User.GetUserId();

            mDset = mFloorBLL.SeatBookCheckRights(mCurrUsrId, Configuration);

            return Json(new
            {
                IsSuccess = "Y",
                ReturnVal = JsonConvert.SerializeObject(mDset)
            });
        }

        // Get All Seat Search List
        [HttpPost]
        public IActionResult SeatSearchList(string vLastName, string vFirstName, string vFloorId, string vDeptId, string vSrchType)
        {
            FloorBLL mFloorBLL = null;
            DataSet mDset = null;
            String vCurrUsrId = string.Empty;

            mFloorBLL = new FloorBLL();

            vCurrUsrId = User.GetUserId();

            if (vSrchType == "Name")
            {
                vFloorId = string.Empty;
                vDeptId = string.Empty;
            }
            else if (vSrchType == "FLR")
            {
                vLastName = string.Empty;
                vFirstName = string.Empty;
                vDeptId = string.Empty;
            }
            else if (vSrchType == "DPT")
            {
                vLastName = string.Empty;
                vFirstName = string.Empty;
                vFloorId = string.Empty;
            }

            if (!string.IsNullOrEmpty(vFloorId))
                vFloorId = vFloorId.Replace("number:", "");

            mDset = mFloorBLL.SeatSearchList(vLastName, vFirstName, vFloorId, vDeptId, vCurrUsrId, Configuration);

            return Json(JsonConvert.SerializeObject(mDset));
        }

        // View  SeatBook List
        [HttpPost]
        public IActionResult ViewSeatBookList()
        {
            FloorBLL mFloorBLL = null;
            string mCurrUsrId = string.Empty;
            DataSet mDset = new DataSet();

            mFloorBLL = new FloorBLL();
            mCurrUsrId = User.GetUserId();

            mDset = mFloorBLL.ViewSeatBookList(mCurrUsrId, Configuration);

            return Json(new
            {
                IsSuccess = "Y",
                ReturnVal = JsonConvert.SerializeObject(mDset)
            });
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

Views/SeatBook/SeatBookList.cshtml
@model SMSApp.Models.SC.SeatBookSC
@using System.Security.Claims;
@using Microsoft.AspNetCore.Mvc.Razor;
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor;

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

    string? mRoleCode = Context.User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.PrimarySid)?.Value;
}

<script src="~/js/appjs/SeatBook/SeatBookView.js"></script>

<script type="text/javascript">

    function AddFloorUser() {
        window.location.href = '@Url.Action("New","Floor")';
        return false;
    }

</script>

<div ng-controller="SeatBookViewCtrl">
    <div class="col-xl-12 PageMargin">
        <section class="box ">
            <header class="panel_header">
                <h2 class="title float-left" style="width:100% !important">
                    <span>出社・在宅登録</span>
                </h2>
            </header>
            <div class="content-body">
                <div class="row">
                    <div class="col-2 col-md-2 col-lg-2">
                        <div class="form-group">
                            <label class="form-label title">在宅勤務登録</label>
                            <div class="controls">
                                <div class="controls">
                                    <button type="submit" ng-class="IsWFH === '0' ? 'btn btn-primary btnradius' : 'btn btn-default btnradius'" ng-click="IsWorkFromHome()" ng-disabled="IsWFH == '1'">
                                        在宅勤務登録
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-3 col-md-3 col-lg-3">
                        <div class="form-group">
                            <label class="form-label title">退席/勤務終了</label>
                            <div class="controls">
                                <button type="button" ng-class="IsWFH == '0' && IsWorking == '0' ? 'btn btn-default btnradius' : 'btn btn-warning btnradius'"
                                        ng-click="CheckOutSeat();" ng-disabled="IsWFH == '0' && IsWorking == '0'">
                                    退席/勤務終了
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <table id="example-11" class="display table table-hover table-condensed" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th width="10%">Sr No</th>
                                    <th width="30%">フロア名</th>
                                    <th width="35%">フロア詳細</th>
                                    <th width="10%">座席の登録</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr ng-repeat="item in FloorList" ng-if="FloorList.length > 0">
                                    <td ng-bind="item.RowId"></td>
                                    <td ng-bind="item.FloorName"></td>
                                    <td ng-bind="item.FloorDesc"></td>
                                    <td class="text-center">
                                        <span style="cursor:pointer" ng-click="BookSeat(item.FloorId);">
                                            <i class="fa fa-eye"></i>
                                        </span>
                                    </td>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="4">
                                    </td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>